\LoadClass[a4paper,12pt]{article}


%-------- RequirePackages
\RequirePackage{subfiles}
\RequirePackage{listings}
\RequirePackage{graphicx}
\RequirePackage{hyperref}
\RequirePackage[parfill]{parskip}

\RequirePackage{marvosym}
\RequirePackage{wasysym}
\RequirePackage{latexsym}
\RequirePackage{amssymb}
\RequirePackage[table,xcdraw]{xcolor}


%-------- Include
\include{language_defs}


%-------- Package settings
\graphicspath{ {./figures/} }




%-------- Page setup
\textwidth 16cm
\textheight 24cm
\oddsidemargin 0cm
\topmargin -2cm
\def\x{{\bf x}}
\def\w{{\bf w}}
\def\squeeze{\itemsep=0pt\parskip=0pt}

